### ISSUE TITLE
1.1 Compatibility

### ISSUE THREAD

**Issue by DuoDex** [DaMichel/KerbalFlightIndicators#3]
Please to let us know if you are planning to update this to a 1.1 compatible version - I am with child to see it in conjunction with MouseAimFlight.

**Comment by DaWelter** [comment]
Yes, I kept it in the back of my head since 1.1 released. Probably some time soon i'll take a look at it.

**Comment by DaMichel** [comment]
Yes, I kept it in the back of my head since 1.1 released. Probably some time soon i'll take a look at it.
